version: '3.8'
services:
    app:
        build: .
        ports:
        - "8000:8000"
        depends_on:
        - redis
        networks:
        - app-network

    redis:
        image: redis:alpine
        ports:
        - "6379:6379"
        restart: always
        volumes:
        - redis_data:/data
        networks:
        - app-network

volumes:
    redis_data: {}

networks:
    app-network:
        driver: bridge
